services:
  beattie-lms:
    build: .
    container_name: beattie-lms
    restart: unless-stopped
    environment:
      - PUBLIC_API_URL=https://api.beattietech.local
    networks:
      - beattie
    expose:
      - "4321"

networks:
  beattie:
    external: true
